### ISSUE TITLE
Visual design/branding for Bento home

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#12]
tbd

**Comment by jvine** [comment]
![bento-home](https://user-images.githubusercontent.com/6945691/30084508-92afefba-9247-11e7-9f3c-64ebda57d5ff.png)

- Same section as on articles+/catalog home; all 4 links enables and no "you are here"
- Paren graphic will be provided asap (also applies to articles+/catalog home)
- header branding matches library website (rather than SearchWorks)
