### ISSUE TITLE
Metadata improvements for Articles+ block

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#294]
Desired updates:
- Add author (not linked)
- Add abstract w/ 2 line truncation (see #293)
- Improve italicization of journal titles

## Before
![articles-without-metadata-enhancement](https://user-images.githubusercontent.com/5402927/88765773-d70d6680-d12b-11ea-9ee7-c39ae6aa4761.png)

## After
![metdata updates](https://user-images.githubusercontent.com/5402927/88764254-77ae5700-d129-11ea-9003-053ba13d8b12.png)

## Sample records
[Search: "white matter language pathways"](https://library.stanford.edu/all/?utf8=%E2%9C%93&q=white+matter+language+pathways)

- [The contributions of language pathways in white matter to linguistic and cognitive processing after mild traumatic brain injury](https://searchworks.stanford.edu/articles/edspmu__edspmu.S241134842020005X)
- [White Matter Language Pathways and Language Performance in Healthy Adults Across Ages](https://searchworks.stanford.edu/articles/edsdoj__edsdoj.182f94c88dbd43c5b4bc89ac3661f1cf)

**Comment by jkeck** [comment]
What is the desired behavior WRT improving italicization?  In SearchWorks it looks like we attempt to italicize non-italicized titles (based on punctuation) for display in results, but, since this isn't in the EDS data, it's not coming through the API. 

If what we want to do is mimic the italicization that's already occurring in SearchWorks, I can look at injecting our modified composed title to be surfaced through the the API instead of the raw one from EDS.

**Comment by jvine** [comment]
I guess the desired behaviour is to match SearchWorks. I recall geo-Darren did a lot of work on the italicization there.

**Comment by jkeck** [comment]
I've added sul-dlss/SearchWorks#2511 to address that, so that the formatting will just start coming through once we accomplish that.
