### ISSUE TITLE
Implement new Exhibits Search block

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/sul-bento-app#298]
![exhibits-block](https://user-images.githubusercontent.com/5402927/88835557-45811180-d18a-11ea-925c-655596ed54dc.png)

- Add Exhibits as the 5th block (3rd row left) to the search results. 
- Same layout and content as in [SearchWorks Exhibits sidebar](https://searchworks.stanford.edu/view/4769498)
- External link passes the user’s search term(s) to the item search in Exhibits

**Comment by jkeck** [comment]
A small piece of clarification, should this effectively be a "Find items in all exhibits" search whose response is grouped by exhibit? 

If so, should we display the number of items in each exhibit that matched the query (similar to what we show in that result display?)

**Comment by jvine** [comment]
This is meant to use the title/subtitle/description(?) search that populates the typeahead dropdown in Exhibits. Primary use case for Bento, at least initially, is searching for an exhibit title.

**Comment by jkeck** [comment]
Ah, okay, I got confused by the "item search in exhibits" part, but I after reading this more closely I see that's for the "external link" only.

So just to reiterate (and also from gleaning info in #314 and #316) the goal here is to:
* Execute the user's search in bento to Exhibits as an exhibit title (and subtitle) search.
* Pull in *all* the exhibits that match that query through the API (and hide some of them behind a toggle button).
* Provide a link for the user to execute their same search terms in the exhibits app, but instead of searching for exhibits, to search for items instead ("items in all exhibits" search).

**Comment by jkeck** [comment]
And we don't include description in the search FWIW, only title+subtitle.  If we're operating under the assumption that my first bullet above is true, should we still constrain this to a title+subtitle search?

**Comment by jvine** [comment]
Ah I'm being imprecise again. Your statement of goals is correct, and yes, I mean title + subtitle. 

Though I do recall that when we added title search to Exhibits, we speculated that it might be possible/desirable to add the description for the bento search. I think that's a separate issue from this ticket, though.

**Comment by jkeck** [comment]
Yeah, true about description, and I believe we have that data technically available to us, we just aren't searching it.
